use std::collections::HashMap;
use std::time::Duration;
use chrono::DateTime;
use chrono::Utc;
use url::Url;

#[derive(Debug, Clone)]
pub struct MyOption {
    pub input: String,
    pub headers: HashMap<String, String>,
    pub ad_keywords: Option<Vec<String>>,
    pub max_speed: Option<u64>,
    pub keys: Option<Vec<String>>,
    pub base_url: Option<String>,
    pub key_text_file: Option<String>,
    pub url_processor_args: Option<String>,
    pub log_level: String,
    pub no_date_info: bool,
    pub copyright_info: Option<String>,
    pub commnet_info: Option<String>,
    pub no_log: bool,
    pub allow_hls_multi_ext_map: bool,
    pub auto_select: bool,
    pub disable_update_check: bool,
    pub sub_only: bool,
    pub thread_count: usize,
    pub download_retry_count: usize,
    pub http_request_timeout: f64,
    pub live_record_limit: Option<Duration>,
    pub task_start_at: Option<DateTime<Utc>>,
    pub skip_merge: bool,
    pub binary_merge: bool,
    pub force_ansi_console: bool,
    pub no_ansi_color: bool,
    pub use_ffmpeg_concat_demuxer: bool,
    pub del_after_done: bool,
    pub auto_subtitle_fix: bool,
    pub check_segments_count: bool,
    pub skip_download: bool,
    pub write_meta_json: bool,
    pub append_url_params: bool,
    pub mp4_real_time_decryption: bool,
    pub skip_subtitle_decrypt: bool,
    pub skip_audio_decrypt: bool,
    pub force_mux_dolby: bool,
    pub use_shaka_packager: bool,
    pub decryption_engine: String,
    pub mux_after_done: bool,
    pub concurrent_download: bool,
    pub live_real_time_merge: bool,
    pub live_keep_segments: bool,
    pub live_perform_as_vod: bool,
    pub use_system_proxy: bool,
    pub subtitle_format: String,
    pub tmp_dir: Option<String>,
    pub save_dir: Option<String>,
    pub save_name: Option<String>,
    pub save_pattern: Option<String>,
    pub log_file_path: Option<String>,
    pub ui_language: Option<String>,
    pub decryption_binary_path: Option<String>,
    pub ffmpeg_binary_path: Option<String>,
    pub mkvmerge_binary_path: Option<String>,
    pub mux_imports: Option<Vec<String>>,
    pub video_filter: Option<String>,
    pub drop_video_filter: Option<String>,
    pub audio_filter: Option<String>,
    pub drop_audio_filter: Option<String>,
    pub subtitle_filter: Option<String>,
    pub drop_subtitle_filter: Option<String>,
    pub custom_hls_method: Option<String>,
    pub custom_hls_key: Option<String>,
    pub custom_hls_iv: Option<String>,
    pub custom_proxy: Option<Url>,
    pub custom_range: Option<String>,
    pub live_wait_time: Option<u64>,
    pub live_take_count: usize,
    pub mux_options: Option<String>,
    pub live_pipe_mux: bool,
    pub live_fix_vtt_by_audio: bool,
}

impl Default for MyOption {
    fn default() -> Self {
        Self {
            input: String::new(),
            headers: HashMap::new(),
            ad_keywords: None,
            max_speed: None,
            keys: None,
            base_url: None,
            key_text_file: None,
            url_processor_args: None,
            log_level: "INFO".to_string(),
            no_date_info: false,
            copyright_info: None,
            commnet_info: None,
            no_log: false,
            allow_hls_multi_ext_map: false,
            auto_select: false,
            disable_update_check: false,
            sub_only: false,
            thread_count: num_cpus::get(),
            download_retry_count: 3,
            http_request_timeout: 100.0,
            live_record_limit: None,
            task_start_at: None,
            skip_merge: false,
            binary_merge: false,
            force_ansi_console: false,
            no_ansi_color: false,
            use_ffmpeg_concat_demuxer: false,
            del_after_done: true,
            auto_subtitle_fix: true,
            check_segments_count: true,
            skip_download: false,
            write_meta_json: true,
            append_url_params: false,
            mp4_real_time_decryption: false,
            skip_subtitle_decrypt: false,
            skip_audio_decrypt: false,
            force_mux_dolby: false,
            use_shaka_packager: false,
            decryption_engine: "MP4DECRYPT".to_string(),
            mux_after_done: false,
            concurrent_download: false,
            live_real_time_merge: false,
            live_keep_segments: true,
            live_perform_as_vod: false,
            use_system_proxy: true,
            subtitle_format: "SRT".to_string(),
            tmp_dir: None,
            save_dir: None,
            save_name: None,
            save_pattern: None,
            log_file_path: None,
            ui_language: None,
            decryption_binary_path: None,
            ffmpeg_binary_path: None,
            mkvmerge_binary_path: None,
            mux_imports: None,
            video_filter: None,
            drop_video_filter: None,
            audio_filter: None,
            drop_audio_filter: None,
            subtitle_filter: None,
            drop_subtitle_filter: None,
            custom_hls_method: None,
            custom_hls_key: None,
            custom_hls_iv: None,
            custom_proxy: None,
            custom_range: None,
            live_wait_time: None,
            live_take_count: 16,
            mux_options: None,
            live_pipe_mux: false,
            live_fix_vtt_by_audio: false,
        }
    }
}
